### ISSUE TITLE
get database from saltos.db

### ISSUE THREAD

**Issue by zn3x** [josepsanzcamp/SaltOS#4]
/files/saltos.db has a public access
so anyone can get your database

**Comment by josepsanzcamp** [comment]
Thanks by your notice

SaltOS contains a rule "Deny from all" inside the .htaccess file that is placed in the files directory to prevent the issue.

If you are using apache, and you have enable the use of the .htaccess, this must to solve the problem.

But depending on the server that you are using, maybe need some special configuration to prevent the issue.

Could you add more details about the issue that you are living???

**Comment by zn3x** [comment]
Yep , I have seen a vulnerability discover for the ability to get database from saltos.db . I tested this open source in localhost (not apache 2) , and its showing , is it maybe because its just uploaded in localhost ?
and as you mentioned , does the .htaccess hide all saltos.db when you activate it?

**Comment by josepsanzcamp** [comment]
The problem seems to be that your server is not using the htaccess rule.

Could you add more details about what server are you using to test it???

Thanks.

**Comment by zn3x** [comment]
Xampp

**Comment by josepsanzcamp** [comment]
I don't have experience using this compounds of software but I understand that the apache configuration doesn't allow to use the rules contained in the htaccess files.

Please, search the httpd.conf file in your install directory and modify the entry "AllowOverride None" to "AllowOverride All" and restart the apache service. With this modification, your saltos will be use the rules to deny the direct access to the data directories.

**Comment by josepsanzcamp** [comment]
Only to close this issue: SaltOS provide an example of rule using the htaccess method but depending of what server is used in each case, the administrator must to securize the access to the directories that can contain data as files, cache, inbox and outbox.

It's important to prevent an arbitrary access to the database if you are using sqlite3, but if you are using mariadb, too it's important to protect the access to the config.xml file placed to the files directory because this file contains the database credentials.

This level of security is guaranted by saltos if you allow the use of htaccess files in your apache setup by adding a line as "AllowOverride All". This feature is enabled by default if you are using the SaltOS Server based on a Centos 7.
